module.exports = {
//    flushQueue: require('./mpdclient.music.flushQueue.js'),
    getCurrentTrack: require('./mpdclient.music.getCurrentTrack.js'),
//    getMuted: require('./mpdclient.music.getMuted.js'),
    getPlaying: require('./mpdclient.music.getPlaying.js'),
//    getPlaylists: require('./mpdclient.music.getPlaylists.js'),
//    getQueue: require('./mpdclient.music.getQueue.js'),
//    getVolume: require('./mpdclient.music.getVolume.js'),
    next: require('./mpdclient.music.next.js'),
    pause: require('./mpdclient.music.pause.js'),
    play: require('./mpdclient.music.play.js'),
//    playPlaylist: require('./mpdclient.music.playPlaylist.js'),
    previous: require('./mpdclient.music.previous.js'),
//    setMuted: require('./mpdclient.music.setMuted.js'),
    setVolume: require('./mpdclient.music.setVolume.js'),
    stop: require('./mpdclient.music.stop.js'),
};
